// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4-axJyuE91Ex_9j1siXjnLUiJG3GT-_8',
    appId: '1:599302337860:web:868a76dc2d74f8ae8d9311',
    messagingSenderId: '599302337860',
    projectId: 'ubupuroject',
    authDomain: 'ubupuroject.firebaseapp.com',
    databaseURL: 'https://ubupuroject-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ubupuroject.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMp3VWnTV-oZhcOJuLeHXrBsDXFJ_QL54',
    appId: '1:599302337860:android:a11810e3bdaff3388d9311',
    messagingSenderId: '599302337860',
    projectId: 'ubupuroject',
    databaseURL: 'https://ubupuroject-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ubupuroject.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBV9k6s1m3SuCTCReYdQR4y9cQIJd6C1T8',
    appId: '1:599302337860:ios:67bc912e3b89f9fc8d9311',
    messagingSenderId: '599302337860',
    projectId: 'ubupuroject',
    databaseURL: 'https://ubupuroject-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ubupuroject.appspot.com',
    iosClientId: '599302337860-kaatjlomckv5sf36od3vca7125v007tb.apps.googleusercontent.com',
    iosBundleId: 'com.example.newMatch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBV9k6s1m3SuCTCReYdQR4y9cQIJd6C1T8',
    appId: '1:599302337860:ios:67bc912e3b89f9fc8d9311',
    messagingSenderId: '599302337860',
    projectId: 'ubupuroject',
    databaseURL: 'https://ubupuroject-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ubupuroject.appspot.com',
    iosClientId: '599302337860-kaatjlomckv5sf36od3vca7125v007tb.apps.googleusercontent.com',
    iosBundleId: 'com.example.newMatch',
  );
}
